//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos_Chevrolet
    {
        public int Id { get; set; }
        public string Marca_Chevrolet { get; set; }
        public string Modelo_Chevrolet { get; set; }
        public Nullable<int> Cilindraje_Chevrolet { get; set; }
        public Nullable<int> Anio_Chevrolet { get; set; }
        public string Color__Chevrolet { get; set; }
        public string Tipo_Chevrolet { get; set; }
        public string Concesionario_Chevrolet { get; set; }
        public Nullable<System.DateTime> FechaRegistro_Chevrolet { get; set; }
    }
}
